// E10, Varun Shourie, CIS340, Tuesday/Thursday 3:00PM-4:15PM

import java.util.Random;
import java.util.Scanner;

public class Craps {
	
	// Converts a number between 1-6 to its corresponding String value. 
	private static String numberToText(int number) {
		// declares a String to hold the number text.
		String numberText = "";
		
		// depending on what the random number is provided with the 
		// parameter, the number is converted to its corresponding
		// String value. 
		switch(number) {
		case 1: 
			numberText = "ONE";
			break;
		case 2:
			numberText = "TWO";
			break;
		case 3:
			numberText = "THREE";
			break;
		case 4:
			numberText = "FOUR";
			break;
		case 5:
			numberText = "FIVE";
			break;
		case 6:
			numberText = "SIX";
			break;
		}
		
		// returns back the text version of the random number to the calling method.
		return numberText;
	}
	
	// Generates a random number which simulates how a dice rolls in real life. 
	private static int generateRandomNumber() {
		// Declares an instance of the Random class to be able to generate random numbers.
		Random randomGenerator = new Random();
		// Holds the random number generated by the object from the Random class.
		int randomNumber = 0;
		
		// Generates the random number to be used in rolling the dice.
		randomNumber = 1 + randomGenerator.nextInt(6);
		// Returns the random number to the calling method for its usage.
		return randomNumber;
	}
	
	public static void main(String[] args) {
		// Stores the two random numbers to be used in printing output to the console.
		int dieValue1 = 0;
		int dieValue2 = 0;
		// Takes in user input when the user presses the Enter key or presses x. 
		String userInput = "";
		
		// Declares an instance of the Scanner class to take in user input. 
		Scanner scanner = new Scanner(System.in);
		
		// Welcomes the user to the program.
		System.out.println("\t\t\tCraps Die Roll\n");
		System.out.println("Press Enter to roll a pair of dice...");
		scanner.nextLine();
		
		// A do loop is used since the loop must run once. This loop relies on sentinel-controlled repetition
		// to keep on printing out two die values for the user until the user opts out of the loop through
		// entering the sentinel value. Upon doing so, the program effectively terminates. 
		do {
			// Creates the first random number to be used in the application and prints the number.
			dieValue1 = generateRandomNumber();
			System.out.printf("Rolling die.... %s\n", numberToText(dieValue1));
			// Creates the second random number to be used in the application and prints the number.
			dieValue2 = generateRandomNumber();
			System.out.printf("Rolling die.... %s\n", numberToText(dieValue2));
			
			// If the die values equal 6 for both of the die, then the user has rolled a boxcar.
			if(dieValue1 == 6 && dieValue2 == 6) {
				System.out.println("You rolled a boxcar!");
			}
			// If the die values equal 1 for both of the die, then the user has rolled snake eyes.
			else if(dieValue1 == 1 && dieValue2 == 1) {
				System.out.println("You rolled snake eyes!");
			}
			
			System.out.println();
			
			// Prompts the user and asks them if they want to see random values again
			// from rolling the metaphorical dice. 
			System.out.print("Type x to exit or press Enter to roll again... ");
			userInput = scanner.nextLine();
			
		} while (!userInput.equalsIgnoreCase("X"));
		
		
	}
	
}
